-- Braca Store Database Seed Data
-- For XAMPP MySQL/phpMyAdmin
-- Run this after schema.sql

USE ecommerce_db;

-- Insert Admin User (password: admin123 - hashed with bcrypt)
-- Default password hash for 'admin123' using bcrypt
INSERT INTO users (username, email, password, role) VALUES
('admin', 'admin@bracastore.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJqOqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'admin')
ON DUPLICATE KEY UPDATE username=username;

-- Note: The password hash above is a placeholder. 
-- The actual hash will be generated by the Node.js application.
-- To create the admin user properly, either:
-- 1. Register through the app and then update the role in database, OR
-- 2. Run the Node.js seed script: npm run seed

-- Insert Sample Products
INSERT INTO products (name, description, price, category, image_url, stock) VALUES
('Product 1', 'High-quality product from Braca Store', 79.99, 'T-Shirt', '/images/top1.png', 50),
('Product 2', 'Premium training gear', 99.99, 'Training', '/images/top2.png', 30),
('Product 3', 'Exclusive memorabilia item', 49.99, 'Memorabilia', '/images/top3.png', 20),
('Product 4', 'Comfortable and stylish t-shirt', 39.99, 'T-Shirt', '/images/top4.png', 40),
('Product 5', 'Limited edition t-shirt', 199.99, 'T-Shirt', '/images/top5.png', 15),
('Product 6', 'Rare collectible memorabilia', 199.99, 'Memorabilia', '/images/top6.png', 10),
('Product 7', 'Exclusive memorabilia piece', 199.99, 'Memorabilia', '/images/top7.png', 12),
('Product 8', 'Professional training equipment', 799.99, 'Training', '/images/top8.png', 8),
('Product 9', 'Premium training gear set', 899.99, 'Training', '/images/top9.png', 5)
ON DUPLICATE KEY UPDATE name=name;

